const data=require('../fixtures/Prospect.json')
describe('Prospect_flow', () =>{


   
   it('Verify Begin_Screen',  () =>{
       cy.visit(data.Prospect_url)
       cy.wait(1000)
       cy.contains('Hey, Sonakshi Singh')
       .should('have.text', 'Hey, Sonakshi Singh')
       cy.log('Hey,Sonakshi singh messsage is displayed' )
       cy.get(':nth-child(3) > .typo > .MuiGrid-root > :nth-child(1)')
       cy.contains('You’re about 5 minutes away from a no-bullshit').should('be.visible')
       cy.contains('price quote for a wholly soul-cleansing').should('be.visible')
       cy.contains('alternative for your linen needs').should('be.visible')
       cy.contains('Begin').should('be.enabled').click()
       cy.log('clicked on Begin button')
       cy.wait(1000)
   })
   it('Verify splash_screen1',  () =>{
       cy.contains('The Best Damn Cotton Napkins')
       .should('be.visible')
       cy.log('The Best Damn Cotton Napkins message is displayed')
       cy.contains('Delivered Daily')
       .should('be.visible')
       cy.log('Delivered Daily message is displayed')
        cy.contains('Polyester can’t absorb a damn thing!')
       .should('be.visible')
       cy.log("Our napkins and towels are woven message is displayed")  
       cy.contains('Polyester can’t absorb a damn thing!')
       .should('be.visible')
       cy.log("Our napkins and towels are woven message is displayed")
       cy.contains('with 100% ultra-soft cotton.')
       .should('be.visible')
       cy.log("with 100% ultra-soft cotton. message is displayed") 
       cy.contains('We swap ‘em out every day, so they’re fresh')
       .should('be.visible')
       cy.log("We swap ‘em out every day, so they’re fresh message is displayed")
       cy.contains("like rain, and they fit snugly in ‘tu casa’")
       .should('be.visible')
       cy.log("like rain, and they fit snugly in ‘tu casa’ message is displayed")
       cy.get('[tabindex="0"] .MuiSvgIcon-root').click()
       cy.get('.MuiMobileStepper-root > [tabindex="0"] ').click({multiple: true})
      

    })
      
    it('Verify splash_screen2',  () =>{
       cy.contains('No Contracts')
       .should('be.visible')
       cy.log('No Contracts message is displayed')
       cy.contains('No Hidden Fees')
       .should('be.visible')
       cy.log('No Hidden Fees message is displayed')
        cy.contains('One transparent fee.')
       .should('be.visible')
       cy.log("One transparent fee. message is displayed")  
       cy.contains('No nickels. No dimes.')
       .should('be.visible')
       cy.log("No nickels. No dimes. message is displayed")
       cy.contains('Not even inventory maintenance fees.')
       .should('be.visible')
       cy.log("Not even inventory maintenance fees. message is displayed")
       cy.contains('Go online to adjust your usage anytime.')
       .should('be.visible')
       cy.log("Go online to adjust your usage anytime. message is displayed")
       cy.contains('Cancel anytime.')
       .should('be.visible')
       cy.log("Cancel anytime. message is displayed")
       cy.get('.MuiMobileStepper-root > [tabindex="0"] ').click({multiple: true})
       cy.contains('Skip Intro').click()
    })

   it('Verify Product_list_screen',  () =>{
        cy.get('.MuiBottomNavigation-root > :nth-child(3)').click()
        cy.log('Clicked on BOH category')
        cy.get(':nth-child(2) > .MuiBottomNavigationAction-wrapper')
        .click()
        cy.wait(2000)
        cy.log('Clicked on FOH category')
        //cy.get('.MuiButtonBase-root.Mui-selected')
        //.click()
   })
        


  it('Selecting Products from list',  () =>{
      cy.get('.MuiBottomNavigation-root > :nth-child(1)').click()
      cy.wait(1000)
      cy.get('.MuiFab-label').eq(0)
      .click()
      cy.get('.MuiFab-label').eq(1)
      .click()
      cy.wait(1000)
      cy.log('Selected two products from list')
      cy.contains('Quote Me').click()
      cy.log('Successfully clicked on Quote Me')
      cy.wait(2000)
    })
  it('Verify Cart page',  () =>{

      cy.contains('How many do you need weekly?')
      .should('be.visible')
      cy.log('How many do you need weekly? message is displayed') 
      cy.contains('Hit us with your best shot')
      .should('be.visible')
      cy.log('Hit us with your best shot message is displayed') 
      cy.contains('Weekly Usage').should('be.visible')
      cy.log('Weekly usage is displayed')
    })

      it('Verify Add more products',  () =>{
      cy.contains('Add more Products')
      .should('be.visible')
      cy.log('Add more Product option is displayed')
      cy.contains('Add more Products').click()
      cy.wait(1000)
      cy.get('.MuiFab-label').eq(3)
      .click()
      cy.log('Added one more product')
      cy.contains('Quote Me').click()
      cy.log('Successfully clicked on Quote Me')
      }) 

      it('Verify the quotation of selected Products',  () =>{
      
      cy.get('.MuiInputBase-input.MuiInput-input').eq(0).type('0')
      cy.log('Edited the quantity')
      cy.contains('YOU PAY').should('be.visible')
      cy.log('Total amount is displayed')
      cy.contains('Next').click()
      cy.log('Clicked on Next button')
      cy.wait(5000)
    })

   /*it('Verify search functionality',  () =>{  
    cy.get('.MuiInputBase-input').type('mic')
    cy.wait(1000)
    cy.log('Searching product')     //search functionality
    cy.get('.MuiInputBase-input').clear()
 })*/
 it('Verify Tango_screen',  () =>{ 
       cy.contains('Ready to Tango?')
       .should('be.visible')
       cy.log('Ready to Tango? message is displayed')
       cy.get('input[type="radio"]').check(['Yes'])
       cy.contains("Fucking A! If you'll give us your digits")
       .should('be.visible')
    
   })
  it("When select Yeah,Let's do it",  () =>{ 
      cy.contains("Fucking A! If you'll give us your digits")
       .should('be.visible')
      cy.contains("we'll get this ball rolling...")
      .should('be.visible')
      cy.get('input[name="OrganizationName"]')
      .should('have.value', data.OrganizationName)
      cy.log('Checked Organization Name')
      cy.get('input[name="ContactName"]')
      .should('have.value', data.UserName)
      cy.log('Checked User name')
      cy.get('input[name= "MobileNumber"]')
      .should('have.value', data.MobileNumber)
      cy.log('Checked Mobile NUmber')
      cy.get('input[name="Email"]')
      .should('have.value',data.Email)
      cy.log('Checked Email id')
      cy.get(' img[alt="Back Button"]')
      .should('be.visible')
      cy.log('Back button is visible')
      cy.contains('Submit').click()
      cy.log('Clicked on Submit button')
      cy.wait(2000)
      
     })



  it("Verify Success_screen",  () =>{ 
       cy.contains('Swell!!')
       .should('be.visible')
       cy.contains("We can't wait to get started!")
       .should('be.visible')
       cy.contains('Eric is going to hit you up soon to discuss important details')
       .should('be.visible')
       cy.contains(data.AdminName)
       .should('be.visible')
       cy.contains(data.Admin_Id)
       .should('be.visible')
       cy.contains(data.AdminNumber)
       .should('be.visible')
       cy.log("Eric's details should be displayed")
       cy.contains('Refer a Friend')
       .click() 

       })


  it("Verify Refer_a_Friend_screen",  () =>{ 
        cy.contains('Sweet! Preach it!')  
        .should('be.visible')
        cy.log('Sweet! Preach it! message to be displayed')
        cy.get(':nth-child(2) > .form_field .MuiGrid-root')
        .type(data["Friend's Name"])
        cy.get(':nth-child(3) > .form_field > .MuiGrid-root ')
        .type(data.MobileNumber)
        cy.get('img[alt="Back Button"]')
        .should('be.visible')
        cy.log('Back button is visible')
        cy.contains('Text it').click()
        cy.log('Clicked on Tetx it button')
        cy.wait(2000)
       })


    it('Verify Add more products',  () =>{
        cy.contains('The deed is done.')
        .should('be.visible')
        cy.contains('Thanks for spreading the word!')
        cy.log('The deed is done. Thanks for spreading the word! message is displayed')
        cy.contains('Refer another Friend')
        .should('be.visible')
        cy.log('Refre Another Friend button is displayed')
        cy.contains('Get started again')
       .should('be.visible')
        cy.log('Get started again option should be displayed')
       

    })

   it('Verify Get started Again',  () =>{
        cy.contains('Get started again').click()

        cy.get('.MuiFab-label').eq(0)
        .click()
        cy.get('.MuiFab-label').eq(1)
        .click()
        cy.wait(1000)
        cy.log('Selected two products from list')
        cy.contains('Quote Me').click()
        cy.log('Successfully clicked on Quote Me')
        cy.wait(2000)
        cy.get('.MuiInputBase-input.MuiInput-input').eq(0).type('0')
        cy.log('Edited the quantity')
        cy.contains('YOU PAY').should('be.visible')
        cy.log('Total amount is displayed')
        cy.contains('Next').click()
        cy.log('Clicked on Next button')
        cy.wait(5000)
        
       })
    it('When seleceted Not yet,let me chew on this',  () =>{
      
       cy.get('input[type="radio"]').check(['No'])
       cy.contains('Heard! You put on that thinking cap.')
       .should('be.visible')
       cy.contains("We'll send you your quote to mull over.")
       .should('be.visible')
       cy.get('input[name="OrganizationName"]')
      .should('have.value', data.OrganizationName)
       cy.log('Checked Organization Name')
       cy.get('input[name="ContactName"]')
       .should('have.value', data.UserName)
      cy.log('Checked User name')
       cy.get('input[name= "MobileNumber"]')
       .should('have.value', data.MobileNumber)
       cy.log('Checked Mobile NUmber')
        cy.get('input[name="Email"]')
       .should('have.value',data.Email)
       cy.log('Checked Email id')
       cy.get(' img[alt="Back Button"]')
       .should('be.visible')
       cy.log('Back button is visible')
       cy.contains('Submit').click()
       cy.log('Clicked on Submit button')
       cy.wait(3000)
       
       })

    it("Verify Waiting_screen",  () =>{ 
      
      cy.contains("We'll just sit tight till we hear from you again")
      .should('be.visible')
      cy.contains(data.AdminName)
      .should('be.visible')
      cy.contains(data.Admin_Id)
      .should('be.visible')
      cy.contains(data.AdminNumber)
      .should('be.visible')
      cy.log("Eric's details should be displayed")
      
      

       })
}) 